name: meter_reading_app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # native_opencv:
  #   path: native_opencv

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # https://pub.dev/packages/camera
  camera: ^0.10.5+8
  # https://pub.dev/packages/multiple_result
  multiple_result: ^5.1.0
  # https://pub.dev/packages/cached_network_image
  cached_network_image: ^3.2.3
  # https://pub.dev/packages/flutter_riverpod
  flutter_riverpod: ^2.4.0
  # https://pub.dev/packages/freezed_annotation
  freezed_annotation: ^2.4.1
  # https://pub.dev/packages/shared_preferences
  shared_preferences: ^2.2.1
  # https://pub.dev/packages/flutter_screenutil
  flutter_screenutil:
  flutter_svg: ^2.0.7
  # https://pub.dev/packages/logging
  logging: ^1.2.0
  # https://pub.dev/packages/connectivity_plus
  connectivity_plus: ^4.0.2
  # https://pub.dev/packages/rxdart
  rxdart: any #any version for flutter_google_places
  # https://pub.dev/packages/json_annotation
  json_annotation: ^4.8.1
  permission_handler: ^11.0.0
  image_picker: ^1.0.4
  # https://pub.dev/packages/collection
  collection: ^1.17.2
  # https://pub.dev/packages/animations
  animations: ^2.0.8
  # https://pub.dev/packages/jiffy
  jiffy: ^6.2.1
  fluttertoast: ^8.2.2
  # https://pub.dev/packages/image_cropper
  image_cropper:
  # https://pub.dev/packages/flutter_local_notifications
  flutter_local_notifications: ^16.1.0
  # https://pub.dev/packages/image_gallery_saver
  image_gallery_saver: "^2.0.3"
  # https://pub.dev/packages/device_info_plus
  device_info_plus: ^9.1.1
  # https://pub.dev/packages/path_provider
  path_provider: ^2.1.2
  # https://pub.dev/packages/image
  image: ^4.1.4
  # https://pub.dev/packages/firebase_core
  firebase_core: ^2.20.0
  # https://pub.dev/packages/firebase_crashlytics
  firebase_crashlytics: ^3.4.2
  # https://pub.dev/packages/firebase_analytics
  firebase_analytics: ^10.6.2
  # https://pub.dev/packages/firebase_database
  firebase_database: ^10.3.3
  # https://pub.dev/packages/cloud_firestore
  cloud_firestore: ^4.12.2
  # https://pub.dev/packages/firebase_messaging
  firebase_messaging: ^14.7.8
  # https://pub.dev/packages/firebase_storage
  firebase_storage: ^11.5.5
  # https://pub.dev/packages/syncfusion_flutter_pdf
  syncfusion_flutter_pdf: ^24.1.47
  # https://pub.dev/packages/external_path
  external_path: ^1.0.3
  # https://pub.dev/packages/http
  http: ^1.2.0
  # https://pub.dev/packages/retrofit
  retrofit: ^4.0.1
  # https://pub.dev/packages/dio
  dio: ^5.3.2
  # https://pub.dev/packages/dio_http_formatter
  dio_http_formatter: ^3.2.0
  # https://pub.dev/packages/injectable
  injectable: ^2.3.0
  # https://pub.dev/packages/envied
  envied: ^0.3.0+3
  # https://pub.dev/packages/syncfusion_flutter_datepicker
  syncfusion_flutter_datepicker:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner:
  flutter_gen:
  flutter_gen_runner:
  # https://pub.dev/packages/freezed
  freezed: ^2.4.1
  # https://pub.dev/packages/retrofit_generator
  retrofit_generator: ^7.0.8
  # https://pub.dev/packages/json_serializable
  json_serializable: ^6.7.1
  # https://pub.dev/packages/envied_generator
  envied_generator: ^0.3.0+3

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/tessdata/
    - assets/icons/
    - assets/imgs/
  fonts:
    - family: Poppins
      fonts:
        - asset: google_fonts/poppins-regular.ttf
        - asset: google_fonts/poppins-bold.ttf
        - asset: google_fonts/poppins-medium.ttf

flutter_gen:
  output: lib/generated/
  integrations:
    flutter_svg: true
